CREATE TABLE students_admission_info
(
  StudentId varchar2(50) not null,
  StudentAdmisionNo INTEGER,
  s_admission_date DATE not null,
  s_aadhar_no INTEGER,  
  s_suar_name varchar2(30),
  s_full_name varchar2(30),
  s_dob DATE,
  s_studing_class  varchar2(10) not null,
  s_previous_studing_class varchar2(10),
  s_medium varchar2(8),
  s_tc_no INTEGER,
  StudentStatus varchar2(10) not null,
  s_f_suar_name varchar2(30),
  s_f_full_name varchar2(30),
  s_m_suar_name varchar2(30),
  s_m_full_name varchar2(30),
  s_address varchar2(200),
  s_phone_no INTEGER,
  s_photo BLOB,
  s_gender varchar(10),
  s_caste varchar(10),
  s_religion varchar(10),
  school_code INTEGER,
  TeacherId varchar2(06),
  student_fingerprint BLOB,  
  LOAD_TS TIMESTAMP(6),
  UPD_TS TIMESTAMP(6),
  CONSTRAINT StudentId_info_pk PRIMARY KEY(StudentId),
  CONSTRAINT s_aadhar_no_info_uk UNIQUE(s_aadhar_no)
 );