<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/osb/HRMSIntegrationProject/CreateOrUpdateEmpData" name="CreateOrUpdateEmpData-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="CreateOrUpdateEmpData.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/osb/HRMSIntegrationProject/CreateOrUpdateEmpData"/>
    <wsdl:binding name="CreateOrUpdateEmpData_ptt-binding" type="cre:CreateOrUpdateEmpData_ptt" xmlns:cre="http://xmlns.oracle.com/pcbpel/adapter/db/osb/HRMSIntegrationProject/CreateOrUpdateEmpData">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="insert">
            <soap:operation soapAction="insert"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
        <wsdl:operation name="update">
            <soap:operation soapAction="update"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
        <wsdl:operation name="CreateOrUpdateEmpDataSelect">
            <soap:operation soapAction="CreateOrUpdateEmpDataSelect"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>