<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ServiceBusApplicationgit/HRMSIntegrationProject/CreateStudentID" name="CreateStudentID-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="CreateStudentID.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ServiceBusApplicationgit/HRMSIntegrationProject/CreateStudentID"/>
    <wsdl:binding name="CreateStudentID_ptt-binding" type="cre:CreateStudentID_ptt" xmlns:cre="http://xmlns.oracle.com/pcbpel/adapter/db/ServiceBusApplicationgit/HRMSIntegrationProject/CreateStudentID">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="CreateStudentID">
            <soap:operation soapAction="CreateStudentID"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>