CREATE TABLE STUDENTS_ADMISSION_MASTER 
(
  STUDENTID NUMBER(*, 0) NOT NULL 
, STUDENTNAME VARCHAR2(200 BYTE) NOT NULL 
, STUDENTJOININGCLASS VARCHAR2(10 BYTE) NOT NULL 
, STUDENTADMISSIONDATE DATE NOT NULL 
, STUDENTADMISIONNO NUMBER(*, 0) 
, STUDENTAADHAARNO NUMBER(*, 0) 
, STUDENTCELLNO NUMBER(*, 0) 
, STUDENTSTATUS VARCHAR2(10 BYTE) NOT NULL 
, STUDENTPHOTO BLOB 
, STUDENTJOININGACADEMICYEAR VARCHAR2(10 BYTE) NOT NULL 
, TEACHERID VARCHAR2(6 BYTE) 
, READFLAG CHAR(1 BYTE) 
, LOAD_TS TIMESTAMP(6) 
, UPD_TS TIMESTAMP(6) 
, STUDENTFINGERPRINT BLOB 
, CONSTRAINT STUDENTID_PK PRIMARY KEY 
  (
    STUDENTID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX STUDENTID_PK ON STUDENTS_ADMISSION_MASTER (STUDENTID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
LOB (STUDENTPHOTO) STORE AS SYS_LOB0000029731C00009$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  RETENTION 
  NOCACHE 
  LOGGING 
  TABLESPACE SYSTEM 
  STORAGE 
  ( 
    INITIAL 65536 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS UNLIMITED 
    FREELISTS 1 
    FREELIST GROUPS 1 
    BUFFER_POOL DEFAULT 
  )  
) 	
LOB (STUDENTFINGERPRINT) STORE AS SYS_LOB0000029731C00015$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  RETENTION 
  NOCACHE 
  LOGGING 
  TABLESPACE SYSTEM 
  STORAGE 
  ( 
    INITIAL 65536 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS UNLIMITED 
    FREELISTS 1 
    FREELIST GROUPS 1 
    BUFFER_POOL DEFAULT 
  )  
);

CREATE UNIQUE INDEX STUDENTID_PK ON STUDENTS_ADMISSION_MASTER (STUDENTID ASC) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE STUDENTS_ADMISSION_MASTER
ADD CONSTRAINT S_AADHAR_NO_UK UNIQUE 
(
  STUDENTAADHAARNO 
)
USING INDEX 
(
    CREATE UNIQUE INDEX S_AADHAR_NO_UK ON STUDENTS_ADMISSION_MASTER (STUDENTAADHAARNO ASC) 
    LOGGING 
    TABLESPACE SYSTEM 
    PCTFREE 10 
    INITRANS 2 
    STORAGE 
    ( 
      INITIAL 65536 
      NEXT 1048576 
      MINEXTENTS 1 
      MAXEXTENTS UNLIMITED 
      FREELISTS 1 
      FREELIST GROUPS 1 
      BUFFER_POOL DEFAULT 
    ) 
    NOPARALLEL 
)
 ENABLE;
